import * as mongoose from "mongoose";
import Counter from "./counter";

export interface IAnnouncementModel extends mongoose.Document {
  id: number;
  contestId: number;
  title: string;
  alias: string;
  author: number;
  abstract?: string;
  content: string;
  views: number;
  priority: number;
  createdAt: Date;
  createdBy: number;
  updatedAt: Date;
  updatedBy: number;
}

/**
 * Announcement Schema
 */
const announcementSchema = new mongoose.Schema(
  {
    id: { type: Number, unique: true }, // use auto-increment id, instead of _id generated by database
    contestId: { type: Number, required: true },
    title: { type: String, required: true },
    alias: { type: String, required: true },
    author: { type: Number, required: true },
    abstract: String, // used for preview
    content: { type: String, required: true }, // markdown string
    views: { type: Number, default: 0 },
    priority: { type: Number, default: 1 },
    createdAt: { type: Date, default: Date.now },
    createdBy: Number,
    updatedAt: { type: Date, default: Date.now },
    updatedBy: Number
  },
  {
    collection: "announcements"
  }
);

/**
 * Enable auto-increment
 * DO NOT USE ARROW FUNCTION HERE
 * Problem of `this` scope
 */
announcementSchema.pre("save", function(next) {
  Counter.findByIdAndUpdate(
    "announcement",
    { $inc: { count: 1 } },
    { new: true, upsert: true },
    (err, counter: any) => {
      if (err) {
        return next(err);
      }
      this.id = counter.count;
      next();
    }
  );
});

export default mongoose.model<IAnnouncementModel>(
  "Announcement",
  announcementSchema
);
