import mongoose from "mongoose";
import counter from "./counter";

const articleSchema = new mongoose.Schema(
  {
    id: Number, // use auto-increment id, instead of _id generated by database
    title: String, // “TensorFlow 初探”
    alias: String, // for SEO and URL, “tensor-flow-first-look”
    authorId: Number,
    abstract: String,
    image: String, // title image
    content: String, // markdown
    views: Number,
    likes: Number,
    likers: [Number], // likers' ids
    tags: [String],
    createdAt: { type: Date, default: Date.now },
    createdBy: Number,
    updatedAt: { type: Date, default: Date.now },
    updatedBy: Number
  },
  {
    collection: "articles"
  }
);

/**
 * DO NOT USE ARROW FUNCTION HERE
 * problem of `this`
 */
articleSchema.pre("save", function(next) {
  const doc = this;
  counter.findByIdAndUpdate(
    "article",
    { $inc: { count: 1 } },
    { new: true, upsert: true },
    (err, counter) => {
      if (err) return next(err);
      doc.id = counter.count;
      next();
    }
  );
});

export default mongoose.model("Article", articleSchema);
