import mongoose from "mongoose";
import Counter from "./counter";

export interface ItemModel extends mongoose.Document {
  id: number;
  name: string;
  description?: string;
  total: number;
  left: number;
  createdAt: Date;
  createdBy: number;
  updatedAt: Date;
  updatedBy: number;
}

const itemSchema = new mongoose.Schema<ItemModel>(
  {
    id: { type: Number, unique: true }, // use auto-increment id, instead of _id generated by database
    name: { type: String, required: true },
    description: String,
    total: { type: Number, required: true },
    left: { type: Number, required: true },
    createdAt: { type: Date, default: Date.now },
    createdBy: Number,
    updatedAt: { type: Date, default: Date.now },
    updatedBy: Number
  },
  {
    collection: "items"
  }
);

itemSchema.pre<ItemModel>("save", function(next) {
  Counter.findByIdAndUpdate(
    "item",
    { $inc: { count: 1 } },
    { rawResult: true, new: true, upsert: true },
    (err, counter) => {
      if (err) {
        return next(err);
      }
      this.id = counter.count;
      next();
    }
  );
});

export default mongoose.model<ItemModel>("Item", itemSchema);
