import mongoose from "mongoose";
import counter from "./counter";

/**
 * Item schema
 */
const itemSchema = new mongoose.Schema(
  {
    id: { type: Number, unique: true }, // use auto-increment id, instead of _id generated by database
    name: { type: String, required: true },
    description: String,
    total: { type: Number, required: true },
    left: { type: Number, required: true },
    createdAt: { type: Date, default: Date.now },
    createdBy: Number,
    updatedAt: { type: Date, default: Date.now },
    updatedBy: Number
  },
  {
    collection: "items"
  }
);

/**
 * Enable auto-increment
 * DO NOT USE ARROW FUNCTION HERE
 * Problem of `this` scope
 */
itemSchema.pre("save", function(next) {
  const doc = this;
  counter.findByIdAndUpdate(
    "item",
    { $inc: { count: 1 } },
    { new: true, upsert: true },
    (err, counter) => {
      if (err) return next(err);
      doc.id = counter.count;
      next();
    }
  );
});

export default mongoose.model("Item", itemSchema);
