import mongoose from "mongoose";
import counter from "./counter";

const reservationSchema = new mongoose.Schema(
  {
    id: { type: Number, unique: true }, // use auto-increment id, instead of _id generated by database
    itemId: { type: Number, required: true }, // 预约物品的 id
    userId: { type: Number, required: true }, //预约者 id
    from: { type: Date, required: true },
    to: { type: Date, required: true },
    reason: String,
    approved: { type: Boolean, default: false },
    createdAt: { type: Date, default: Date.now },
    createdBy: Number,
    updatedAt: { type: Date, default: Date.now },
    updatedBy: Number
  },
  {
    collection: "reservations"
  }
);

/**
 * DO NOT USE ARROW FUNCTION HERE
 * problem of `this`
 */
reservationSchema.pre("save", function(next) {
  const doc = this;
  counter.findByIdAndUpdate(
    "reservation",
    { $inc: { count: 1 } },
    { new: true, upsert: true },
    (err, counter) => {
      if (err) return next(err);
      doc.id = counter.count;
      next();
    }
  );
});

export default mongoose.model("Reservation", reservationSchema);
