import * as mongoose from "mongoose";
import Counter from "./counter";

export interface ITeamModel extends mongoose.Document {
  id: number;
  contestId: number;
  name: string;
  description: string;
  leader: number;
  members: number[];
  inviteCode: string;
  available: boolean;
  createdAt: Date;
  createdBy: number;
  updatedAt: Date;
  updatedBy: number;
  isAlive: boolean;
}

/**
 * Team schema
 */
const teamSchema = new mongoose.Schema(
  {
    id: { type: Number, unique: true }, // use auto-increment id, instead of _id generated by database
    contestId: { type: Number, required: true },
    name: { type: String, required: true },
    description: { type: String, required: true },
    leader: { type: Number, required: true },
    members: { type: [Number], required: true },
    inviteCode: { type: String, required: true },
    available: { type: Boolean, default: true },
    createdAt: { type: Date, default: Date.now },
    createdBy: Number,
    updatedAt: { type: Date, default: Date.now },
    updatedBy: Number,
    isAlive: { type: Boolean, default: true }
  },
  {
    collection: "teams"
  }
);

/**
 * Enable auto-increment
 * DO NOT USE ARROW FUNCTION HERE
 * Problem of `this` scope
 */
teamSchema.pre("save", function(next) {
  Counter.findByIdAndUpdate(
    "team",
    { $inc: { count: 1 } },
    { new: true, upsert: true },
    (err, counter: any) => {
      if (err) {
        return next(err);
      }
      this.id = counter.count;
      next();
    }
  );
});
const Team = mongoose.model<ITeamModel>("Team", teamSchema);
Team.updateMany(
  { isAlive: { $exists: false } },
  { $set: { isAlive: true } },
  (err, data) => {
    if (err) console.log(err);
    if (data.nModified) console.log("team", data);
  }
);
export default Team;
