import mongoose from "mongoose";
import Counter from "./counter";

export interface TimelineModel extends mongoose.Document {
  id: number;
  title: string;
  content: string;
  date: Date;
  createdAt: Date;
  createdBy: number;
  updatedAt: Date;
  updatedBy: number;
}

const timelineSchema = new mongoose.Schema<TimelineModel>(
  {
    id: { type: Number, unique: true }, // use auto-increment id, instead of _id generated by database
    title: { type: String, required: true },
    content: { type: String, required: true },
    date: { type: Date, required: true },
    createdAt: { type: Date, default: Date.now, required: true },
    createdBy: { type: Number, required: true },
    updatedAt: { type: Date, default: Date.now, required: true },
    updatedBy: { type: Number, required: true }
  },
  {
    collection: "timelines"
  }
);

timelineSchema.pre<TimelineModel>("save", function(next) {
  Counter.findByIdAndUpdate(
    "timeline",
    { $inc: { count: 1 } },
    { new: true, upsert: true },
    (err, counter: any) => {
      if (err) {
        return next(err);
      }
      this.id = counter.count;
      next();
    }
  );
});

export default mongoose.model<TimelineModel>("Timeline", timelineSchema);
